import { PinataSDK } from "pinata-web3";

const pinata = new PinataSDK({
  pinataJwt:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiI1ZmViYTQ0Zi0wNzU1LTRiNGYtYjdjZS1iM2Q3OWNjZDQ5OWEiLCJlbWFpbCI6ImtoYW51bWFyMDEwOEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJGUkExIn0seyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiNmU3YzQ3NzhkMzE2NzRiMThjMzEiLCJzY29wZWRLZXlTZWNyZXQiOiIwMWY2YmEwODA0MWFhZmQ0OGZjZGRhNjg5YmJiZWQ1YTdjN2IzOWNkYTQ5NWFmNjAxYTg2YmMzYTliMGRkNzdhIiwiZXhwIjoxNzYxMDYxMjg5fQ.dehJVsnMhqae7xIXRA995iEHdTCJGvUQqschh5QZiI4",
  pinataGateway: "",
  pinataGatewayKey:
    "AKpM9yjCZzo84MvTCrm_rnp5EPMcYS3p51u6okO-_OSs3jKIHt0NCjxc6cnphGXX",
});

export default pinata;
